title: "Reece's Blog"
author: ReeceNich
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website is a test site for me to learn about using GitHub pages
  and Jekyll to create a blog-style website.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ReeceNich # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
